// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_addpersondialog.cpp"
#include "EWIEGA46WW/moc_person.cpp"
#include "EWIEGA46WW/moc_persondelegate.cpp"
#include "EWIEGA46WW/moc_personmodel.cpp"
#include "EWIEGA46WW/moc_widget.cpp"
